version: "2"

services:

  php:
    image: wodby/drupal-php:7.1
    container_name: "${PROFILE_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_SITE_NAME: dev
    links:
      - mailhog:mailhog
      - mariadb:mariadb
#      - solr:solr
    depends_on:
      - mailhog
      - mariadb
#      - solr 
    volumes:
      - ./:/var/www/html:cached

  nginx:
    image: wodby/drupal-nginx:8-1.13-2.4.2
    container_name: "${PROFILE_NAME}_web"
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot 
      NGINX_SERVER_NAME: localhost
    links:
      - mariadb:mariadb
    depends_on:
      - php
    volumes_from:
      - php
    labels:
      - 'traefik.backend=nginx_${PROFILE_NAME}'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${TRAEFIK_HOST}'
 
#  solr:
#    image: solr:6-alpine
#    container_name: "${PROFILE_NAME}_solr"
#    ports:
#      - 8983:8983
#    volumes:
#      - ./solr-config/6.x:/solr-conf/conf
#    entrypoint:
#      - docker-entrypoint.sh
#      - solr-precreate
#      - core1
   

  mailhog:
    image: acidaniel/mailhog
    container_name: "${PROFILE_NAME}_mail"
    restart: always

  mariadb:
    image: wodby/mariadb:10.3-3.6.0
    container_name: "${PROFILE_NAME}_mariadb"
    volumes:
        - ./db:/var/lib/mysql
        #Uncomment next line if you need restore a db backup
        #- ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here
    environment:
      MYSQL_DATABASE: ${PROFILE_NAME}
      MYSQL_USER: ${PROFILE_NAME}
      MYSQL_PASSWORD: ${PROFILE_NAME}
      MYSQL_ROOT_PASSWORD: d8root

  traefik:
    image: traefik
    container_name: "${PROFILE_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '${PROFILE_PORT}:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db:
    driver: "local"
